spring.application.name=telegram-bot

# Server Config (Cho phép Đám mây tự chọn Port, mặc định 8000)
server.port=${PORT:8000}

# Telegram Bot Config
bot.token=${BOT_TOKEN}
bot.username=${BOT_USERNAME}
