spring.application.name=telegram-bot

# Server Config (Cho phép Đám mây tự chọn Port, mặc định 8080)
server.port=${PORT:8080}

# Telegram Bot Config
bot.token=${BOT_TOKEN}
bot.username=${BOT_USERNAME}
